// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
	const computed: typeof import("vue")["computed"];
	const createApp: typeof import("vue")["createApp"];
	const customRef: typeof import("vue")["customRef"];
	const defineAsyncComponent: typeof import("vue")["defineAsyncComponent"];
	const defineComponent: typeof import("vue")["defineComponent"];
	const effectScope: typeof import("vue")["effectScope"];
	const getCurrentInstance: typeof import("vue")["getCurrentInstance"];
	const getCurrentScope: typeof import("vue")["getCurrentScope"];
	const h: typeof import("vue")["h"];
	const inject: typeof import("vue")["inject"];
	const isReadonly: typeof import("vue")["isReadonly"];
	const isRef: typeof import("vue")["isRef"];
}
export {};
